name: 🔨 Build Test

on:
  pull_request:
    paths:
      - '**.go'
      - '**.mod'
  workflow_dispatch:

jobs:  
  build:
    name: Test Builds
    if: ${{ !endsWith(github.actor, '[bot]') }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: projectdiscovery/actions/setup/go@v1

      - name: Build
        run: go build ./...
        working-directory: .
      
      - name: Test
        run: go test ./...
        working-directory: .

      - name: Race Condition Tests
        run: go build -race ./...
        working-directory: .

      - name: Example Code Tests
        run: go build .
        working-directory: examples/
